### ISSUE TITLE
How to run multiple Gekko Docker instances in command line mode

### ISSUE THREAD

**Issue by magicdude4eva** [askmike/gekko#1460]
Can you please confirm how I would be able to run multiple Gekko instances via different Docker images/containers.

The idea is to have each Gekko instance launch with a different configuration (i.e. config-usdbtc.js on Gekko1, config-usd-eth.js on Gekko2 etc)

The reason for this is to initially get Telegram notices and run different configurations.

I am unclear what else I might need to do - so far I think that I need to have a docker-compose like this:
```
server:
  restart: always
  build: ./
  volumes:
    - ./volumes/gekko-usdbtc/history:/usr/src/app/history
    - ./config-usdbtc.js:/usr/src/app/config.js
  links:
    - redis
  environment:
   - HOST
   - PORT
  ports:
    - "${PORT}:${PORT}"

server2:
  restart: always
  image: gekko_server  # optionally, you can still do "build: ./", but it makes more sense to just reuse
  volumes:
    - ./volumes/gekko-usdeth/history:/usr/src/app/history
    - ./config-usdeth.js:/usr/src/app/config.js
  links:
    - redis
  environment:
   - HOST
   - PORT
  ports:
    - "${PORT}:${PORT}"

redis:
  image: redis:latest
  volumes:
    - ./volumes/redis:/data
```

and then adjust `package.json` to remove the `--ui`-option:
```
...
    "start": "node ./gekko --config config.js --ui"
...
```

The `Dockerfile` would need to include the Telegram bot:
```
...
npm install --production redis@0.10.0 talib@1.0.2 tulind@0.8.7 node-telegram-bot-api@0.24.0 pg && \
...
```

Questions:
1) What is Redis used for and will there be an issue if multiple dockers with different currency pairs reference the same Redis?

2) Could you think of any case where this could not work or if I miss something else?
